In [32]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [33]:
dataset = pd.read_csv('insurance (1).csv')

In [34]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

In [35]:
print(X)

[[19 'female' nan 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' nan 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]


In [36]:
print(y)

[0 1 3 ... 0 0 0]


In [37]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,2:4])
X[:, 2:4] = imputer.transform(X[:, 2:4])

In [38]:
print(X)

[[19 'female' 30.56876779026217 0.0 'yes' 'southwest']
 [18 'male' 33.77 1.0 'no' 'southeast']
 [28 'male' 30.56876779026217 3.0 'no' 'southeast']
 ...
 [18 'female' 36.85 0.0 'no' 'southeast']
 [21 'female' 25.8 0.0 'no' 'southwest']
 [61 'female' 29.07 0.0 'yes' 'northwest']]


In [63]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,2,3,4,5,6])])
X = np.array(ct.fit_transform(X))

In [64]:
print(X)

  (0, 1)	1.0
  (0, 2)	1.0
  (0, 4)	1.0
  (0, 6)	1.0
  (0, 8)	1.0
  (0, 10)	1.0
  (0, 13)	1.0
  (1, 0)	1.0
  (1, 3)	1.0
  (1, 4)	1.0
  (1, 6)	1.0
  (1, 8)	1.0
  (1, 10)	1.0
  (1, 12)	1.0
  (2, 0)	1.0
  (2, 2)	1.0
  (2, 4)	1.0
  (2, 7)	1.0
  (2, 8)	1.0
  (2, 10)	1.0
  (2, 22)	1.0
  (3, 1)	1.0
  (3, 2)	1.0
  (3, 4)	1.0
  (3, 6)	1.0
  :	:
  (1334, 6)	1.0
  (1334, 8)	1.0
  (1334, 10)	1.0
  (1334, 12)	1.0
  (1335, 1)	1.0
  (1335, 2)	1.0
  (1335, 4)	1.0
  (1335, 6)	1.0
  (1335, 8)	1.0
  (1335, 10)	1.0
  (1335, 12)	1.0
  (1336, 1)	1.0
  (1336, 2)	1.0
  (1336, 4)	1.0
  (1336, 6)	1.0
  (1336, 8)	1.0
  (1336, 10)	1.0
  (1336, 15)	1.0
  (1337, 1)	1.0
  (1337, 2)	1.0
  (1337, 4)	1.0
  (1337, 6)	1.0
  (1337, 8)	1.0
  (1337, 10)	1.0
  (1337, 55)	1.0


In [70]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [71]:
print(y)

[0 1 3 ... 0 0 0]


In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)


TypeError: Singleton array array(<1338x59 sparse matrix of type '<class 'numpy.float64'>'
	with 9366 stored elements in Compressed Sparse Row format>, dtype=object) cannot be considered a valid collection.

In [69]:
print(X_train)

[[1.0 0.0 -0.46466018864228864 ... 26.6 'no' 'northwest']
 [0.0 1.0 -0.46466018864228864 ... 21.4 'no' 'southwest']
 [1.0 0.0 -0.46466018864228864 ... 37.29 'no' 'southeast']
 ...
 [0.0 0.0 2.152110347395863 ... 34.96 'yes' 'northeast']
 [0.0 0.0 2.152110347395863 ... 22.22 'yes' 'southeast']
 [0.0 1.0 -0.46466018864228864 ... 27.94 'no' 'southeast']]


In [50]:
print(X_test)

[[1.0 0.0 0.0 ... 35.53 'no' 'northwest']
 [1.0 0.0 0.0 ... 31.54 'no' 'northwest']
 [1.0 0.0 0.0 ... 37.0 'no' 'southwest']
 ...
 [0.0 0.0 1.0 ... 38.94 'yes' 'southeast']
 [1.0 0.0 0.0 ... 36.575 'no' 'northwest']
 [1.0 0.0 0.0 ... 26.125 'no' 'northeast']]


In [45]:
print(y_train)

[0 1 0 ... 2 2 1]


In [62]:
print(y_test)

[0 0 0 3 1 3 2 0 0 0 0 2 2 1 0 2 0 3 1 0 0 3 0 0 0 1 3 0 2 0 1 2 3 0 3 0 0
 4 0 1 2 0 3 1 2 0 1 0 0 4 0 2 0 3 1 0 3 0 2 0 0 0 1 0 0 1 3 1 1 0 3 1 0 3
 0 1 1 0 0 2 1 2 1 0 1 2 1 2 2 2 0 3 3 1 0 0 1 2 0 2 0 0 3 0 0 0 0 1 1 0 0
 2 0 3 1 0 5 0 4 0 0 4 1 0 2 3 3 3 2 2 0 1 2 1 0 0 0 0 0 0 0 3 2 0 2 0 1 3
 1 2 1 2 2 1 0 0 1 1 1 0 0 2 1 1 3 0 1 1 0 0 2 0 0 0 0 1 1 3 0 2 0 0 0 1 1
 0 0 1 0 5 2 2 0 1 2 0 4 0 4 1 1 2 3 2 2 0 1 1 0 0 0 1 4 2 2 2 0 3 0 2 0 0
 2 3 0 0 0 0 0 0 2 3 2 3 2 0 2 0 1 1 1 0 1 0 0 3 2 1 1 0 1 1 0 3 0 0 0 1 0
 1 2 1 1 2 0 2 0 0]


In [60]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 2:4] = sc.fit_transform(X_train[:, 2:4])
X_test[:, 2:4] = sc.transform(X_test[:, 2:4])

In [56]:
print(X_train)

[[1.0 0.0 -0.4646601886422971 ... 26.6 'no' 'northwest']
 [0.0 1.0 -0.4646601886422971 ... 21.4 'no' 'southwest']
 [1.0 0.0 -0.4646601886422971 ... 37.29 'no' 'southeast']
 ...
 [0.0 0.0 2.1521103473959022 ... 34.96 'yes' 'northeast']
 [0.0 0.0 2.1521103473959022 ... 22.22 'yes' 'southeast']
 [0.0 1.0 -0.4646601886422971 ... 27.94 'no' 'southeast']]


In [58]:
print(X_test)

[[1.0 0.0 -0.4646601886422971 ... 35.53 'no' 'northwest']
 [1.0 0.0 -0.4646601886422971 ... 31.54 'no' 'northwest']
 [1.0 0.0 -0.4646601886422971 ... 37.0 'no' 'southwest']
 ...
 [0.0 0.0 2.1521103473959022 ... 38.94 'yes' 'southeast']
 [1.0 0.0 -0.4646601886422971 ... 36.575 'no' 'northwest']
 [1.0 0.0 -0.4646601886422971 ... 26.125 'no' 'northeast']]
